### ISSUE TITLE
New XML-based localisation format (DRAFT)

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#336]
@VictorPhilipp If you can dump some basic info in here - even just links to existing C# or xml files or whatever, if it's obvious from looking at them what to do - I'll add a wiki page to document it.

**Comment by krzychu124** [comment]
I've made quick test. 
It's quite easy and seems to be working (at least in the mod options):

- put new translation file in `TLM/TLM/Resources',
- set `Build Action` to `Embedded Resource` in file Properties (Visual Studio),
- add following lines into static constructor of class below:
  - `AVAILABLE_LANGUAGE_CODES.Add("suffix_of_new_language");`
  - `LANGUAGE_LABELS["suffix_of_new_language"] = "lang name in native language";` - label displayed as language option the mod options"

`suffix_of_new_language` has to be the same as suffix of language file in `Resources` 
e.g. `lang_en.txt`, so suffix `en` obviously 😉 

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/a6f24080ec10186136c89e9b93682c51f42d7896/TLM/TLM/UI/Translation.cs#L23-L53

**Comment by aubergine10** [comment]
There isn't a `lang_en.txt` in the resources folder though?

**Comment by aubergine10** [comment]
I'm not sure what this step means:

> * set Build Action to Embedded Resource in file Properties (Visual Studio),

I would assume one just goes to the Resources folder, right-click to add new item, and then select the lang file?

![new_item](https://user-images.githubusercontent.com/1386719/58388665-9b53aa00-8019-11e9-8863-bb8a528106a1.png)

And then edit the `Translation.cs` in the usual manner?

**Comment by aubergine10** [comment]
Ah, after adding file to Resources folder in VS, right-click file > properties, then set Embedded Resource:

![embedded_resource](https://user-images.githubusercontent.com/1386719/58388698-f08fbb80-8019-11e9-9834-d7eb6c25533e.png)

**Comment by aubergine10** [comment]
Also, what are we doing about [`lang_template.txt`](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/master/TLM/TLM/Resources/lang_template.txt)?

Currently our updated [localisation guide](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Localisation) states to use [`lang.txt`](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/master/TLM/TLM/Resources/lang.txt) as that contains the actual text of the locale keys.

**Comment by aubergine10** [comment]
Here's initial draft in the wiki: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Adding-a-new-language

**Comment by VictorPhilipp** [comment]
Oh, you're too quick for me :)

lang_template.txt is there to help translators such that they don't have to remove every English translation from the lang.txt when introducing a new language.

What do you think about moving to XML-based localization files? For example:
![grafik](https://user-images.githubusercontent.com/4333935/58419925-27061e80-808c-11e9-8d7f-2605708ab45f.png)

- 👍 Everything would be in one file, no need to add new resources
- 👍 Translators see all available translations for each key at once which could be helpful
- 👎 Missing translations might be hard to find - tools needed

**Comment by krzychu124** [comment]
I like idea of moving to XML. Then we could automate the process of registering new language.

**Comment by aubergine10** [comment]
We could include a section in the xml for the locales and their captions too:

```xml
...
<Languages>
   <Language lang="en">English</Language>
   <Language lang="fr">Français</Language>
   ...
</Languages>
<Translations>
    <Translation key="Road_type">
        <Value lang="en">Road type</Value>
        <Value lang="fr">Type de route</Value>
        ...
    </Translation>
    ...
</Translations>
...
```

Would we still use `\n` for newlines, or would we start using `<![CDATA[ ... ]]>` stuff?

Also, I think we have to factor in translators too - is using XML making their job more complex or easier? If the current format is easier for them, maybe we could have some sort of build process that converts the `lang_*.txt` in to centralised `lang.xml` file?

Another consideration is RAM consumption - would we be loading and retain whole XML, or would we just parse it to get the relevant strings for the active language?

**Comment by aubergine10** [comment]
Regarding missing translations, we could spit those out to the log file in `DEBUG` builds.

* Get list of languages from the translation xml
* For each `<Translation>`
    * For each `<Language>`
        * If `<Value>` not found for the language, trace details to log file

Better still, if we could dump the info in to a markdown file we could then add that to the repo or wiki so translators know what needs translating in their language. We could also state what percentage each language is at.

If a specific `<Translation>` isn't yet localised to a specific language, the `<Value>` for that language would be omitted from the file. In `RELEASE` builds, when loading the local file, we'd just default to the `<Value lang="en">` for the given `<Translation>` if the desired language is not found.

**Comment by aubergine10** [comment]
I'm making a simple html file to parse the `lang_*.txt` files in order to compile an xml file. If there's anything you want to know about the translations, which can be determined when I parse the files, let me know. :)

**Comment by aubergine10** [comment]
### de is 94% complete. Missing 15 keys:

Start, min/max, Segment, TMPE_Title, Name, Imperial, Gameplay, Overlays, Simulation, Strict, TMPE_TUTORIAL_HEAD_MainMenu, Turn_on_red, Scan_for_known_incompatible_mods_on_startup, Ignore_disabled_mods, Traffic_Manager_detected_incompatible_mods,

### es is 72% complete. Missing 66 keys:

TMPE_Title, Imperial, General, Individual_driving_styles, Simulation, On_roads, Ban_private_cars_and_trucks_on_bus_lanes, default, flow_ratio, wait_ratio, After_min._time_has_elapsed_switch_to_next_step_if, Adaptive_step_switching, Dynamic_lane_section, Percentage_of_vehicles_performing_dynamic_lane_section, Vehicle_restrictions_aggression, Strict, Show_path-find_stats, Remove_this_vehicle, Vehicles_follow_priority_rules_at_junctions_with_timed_traffic_lights, Enable_tutorial_messages, TMPE_TUTORIAL_HEAD_MainMenu, TMPE_TUTORIAL_BODY_MainMenu, TMPE_TUTORIAL_HEAD_JunctionRestrictionsTool, TMPE_TUTORIAL_BODY_JunctionRestrictionsTool, TMPE_TUTORIAL_HEAD_LaneArrowTool, TMPE_TUTORIAL_BODY_LaneArrowTool, TMPE_TUTORIAL_HEAD_LaneConnectorTool, TMPE_TUTORIAL_BODY_LaneConnectorTool, TMPE_TUTORIAL_HEAD_ManualTrafficLightsTool, TMPE_TUTORIAL_BODY_ManualTrafficLightsTool, TMPE_TUTORIAL_HEAD_ParkingRestrictionsTool, TMPE_TUTORIAL_BODY_ParkingRestrictionsTool, TMPE_TUTORIAL_HEAD_PrioritySignsTool, TMPE_TUTORIAL_BODY_PrioritySignsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool, TMPE_TUTORIAL_BODY_SpeedLimitsTool, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool, TMPE_TUTORIAL_HEAD_ToggleTrafficLightsTool, TMPE_TUTORIAL_BODY_ToggleTrafficLightsTool, TMPE_TUTORIAL_HEAD_VehicleRestrictionsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_BODY_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_RemoveJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_RemoveJunction, Public_transport, Prevent_excessive_transfers_at_public_transport_stations, Compact_main_menu, Window_transparency, Overlay_transparency, Remove_this_citizen, Remove_parked_vehicles, Node_is_level_crossing, Experimental_features, Turn_on_red, Also_apply_to_left/right_turns_between_one-way_streets, Scan_for_known_incompatible_mods_on_startup, Ignore_disabled_mods, Traffic_Manager_detected_incompatible_mods, Notify_me_if_there_is_an_unexpected_mod_conflict,

### fr is 97% complete. Missing 8 keys:

Stop, min/max, Segment, Maintenance, Gameplay, Individual_driving_styles, Options, Simulation,

### it is 76% complete. Missing 55 keys:

Stop, min/max, TMPE_Title, Outgoing_demand, Incoming_demand, Parking_AI, Gameplay, Overlays, Individual_driving_styles, Enable_tutorial_messages, TMPE_TUTORIAL_HEAD_MainMenu, TMPE_TUTORIAL_BODY_MainMenu, TMPE_TUTORIAL_HEAD_JunctionRestrictionsTool, TMPE_TUTORIAL_BODY_JunctionRestrictionsTool, TMPE_TUTORIAL_HEAD_LaneArrowTool, TMPE_TUTORIAL_BODY_LaneArrowTool, TMPE_TUTORIAL_HEAD_LaneConnectorTool, TMPE_TUTORIAL_BODY_LaneConnectorTool, TMPE_TUTORIAL_HEAD_ManualTrafficLightsTool, TMPE_TUTORIAL_BODY_ManualTrafficLightsTool, TMPE_TUTORIAL_HEAD_ParkingRestrictionsTool, TMPE_TUTORIAL_BODY_ParkingRestrictionsTool, TMPE_TUTORIAL_HEAD_PrioritySignsTool, TMPE_TUTORIAL_BODY_PrioritySignsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool, TMPE_TUTORIAL_BODY_SpeedLimitsTool, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool, TMPE_TUTORIAL_HEAD_ToggleTrafficLightsTool, TMPE_TUTORIAL_BODY_ToggleTrafficLightsTool, TMPE_TUTORIAL_HEAD_VehicleRestrictionsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_BODY_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_RemoveJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_RemoveJunction, Public_transport, Prevent_excessive_transfers_at_public_transport_stations, Compact_main_menu, Window_transparency, Overlay_transparency, Remove_this_citizen, Remove_parked_vehicles, Node_is_level_crossing, Experimental_features, Also_apply_to_left/right_turns_between_one-way_streets, Scan_for_known_incompatible_mods_on_startup, Ignore_disabled_mods, Traffic_Manager_detected_incompatible_mods, Notify_me_if_there_is_an_unexpected_mod_conflict,

### ja is 97% complete. Missing 6 keys:

TMPE_Title, Individual_driving_styles, TMPE_TUTORIAL_HEAD_MainMenu, Scan_for_known_incompatible_mods_on_startup, Ignore_disabled_mods, Traffic_Manager_detected_incompatible_mods,

### ko is 99% complete. Missing 2 keys:

Individual_driving_styles, TMPE_TUTORIAL_HEAD_MainMenu,

### nl is 71% complete. Missing 67 keys:

Start, Stop, min/max, Segment, Individual_driving_styles, Simulation, On_roads, Ban_private_cars_and_trucks_on_bus_lanes, default, flow_ratio, wait_ratio, After_min._time_has_elapsed_switch_to_next_step_if, Adaptive_step_switching, Dynamic_lane_section, Percentage_of_vehicles_performing_dynamic_lane_section, Vehicle_restrictions_aggression, Strict, Show_path-find_stats, Remove_this_vehicle, Vehicles_follow_priority_rules_at_junctions_with_timed_traffic_lights, Enable_tutorial_messages, TMPE_TUTORIAL_HEAD_MainMenu, TMPE_TUTORIAL_BODY_MainMenu, TMPE_TUTORIAL_HEAD_JunctionRestrictionsTool, TMPE_TUTORIAL_BODY_JunctionRestrictionsTool, TMPE_TUTORIAL_HEAD_LaneArrowTool, TMPE_TUTORIAL_BODY_LaneArrowTool, TMPE_TUTORIAL_HEAD_LaneConnectorTool, TMPE_TUTORIAL_BODY_LaneConnectorTool, TMPE_TUTORIAL_HEAD_ManualTrafficLightsTool, TMPE_TUTORIAL_BODY_ManualTrafficLightsTool, TMPE_TUTORIAL_HEAD_ParkingRestrictionsTool, TMPE_TUTORIAL_BODY_ParkingRestrictionsTool, TMPE_TUTORIAL_HEAD_PrioritySignsTool, TMPE_TUTORIAL_BODY_PrioritySignsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool, TMPE_TUTORIAL_BODY_SpeedLimitsTool, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool, TMPE_TUTORIAL_HEAD_ToggleTrafficLightsTool, TMPE_TUTORIAL_BODY_ToggleTrafficLightsTool, TMPE_TUTORIAL_HEAD_VehicleRestrictionsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_BODY_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_RemoveJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_RemoveJunction, Public_transport, Prevent_excessive_transfers_at_public_transport_stations, Compact_main_menu, Window_transparency, Overlay_transparency, Remove_this_citizen, Remove_parked_vehicles, Node_is_level_crossing, Experimental_features, Turn_on_red, Also_apply_to_left/right_turns_between_one-way_streets, Scan_for_known_incompatible_mods_on_startup, Ignore_disabled_mods, Traffic_Manager_detected_incompatible_mods, Notify_me_if_there_is_an_unexpected_mod_conflict,

### pl is 97% complete. Missing 6 keys:

Start, Stop, min/max, Segment, Individual_driving_styles, TMPE_TUTORIAL_HEAD_MainMenu,

### pt is 72% complete. Missing 66 keys:

min/max, TMPE_Title, Imperial, Gameplay, Individual_driving_styles, Simulation, On_roads, Ban_private_cars_and_trucks_on_bus_lanes, default, flow_ratio, wait_ratio, After_min._time_has_elapsed_switch_to_next_step_if, Adaptive_step_switching, Dynamic_lane_section, Percentage_of_vehicles_performing_dynamic_lane_section, Vehicle_restrictions_aggression, Strict, Show_path-find_stats, Remove_this_vehicle, Vehicles_follow_priority_rules_at_junctions_with_timed_traffic_lights, Enable_tutorial_messages, TMPE_TUTORIAL_HEAD_MainMenu, TMPE_TUTORIAL_BODY_MainMenu, TMPE_TUTORIAL_HEAD_JunctionRestrictionsTool, TMPE_TUTORIAL_BODY_JunctionRestrictionsTool, TMPE_TUTORIAL_HEAD_LaneArrowTool, TMPE_TUTORIAL_BODY_LaneArrowTool, TMPE_TUTORIAL_HEAD_LaneConnectorTool, TMPE_TUTORIAL_BODY_LaneConnectorTool, TMPE_TUTORIAL_HEAD_ManualTrafficLightsTool, TMPE_TUTORIAL_BODY_ManualTrafficLightsTool, TMPE_TUTORIAL_HEAD_ParkingRestrictionsTool, TMPE_TUTORIAL_BODY_ParkingRestrictionsTool, TMPE_TUTORIAL_HEAD_PrioritySignsTool, TMPE_TUTORIAL_BODY_PrioritySignsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool, TMPE_TUTORIAL_BODY_SpeedLimitsTool, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool, TMPE_TUTORIAL_HEAD_ToggleTrafficLightsTool, TMPE_TUTORIAL_BODY_ToggleTrafficLightsTool, TMPE_TUTORIAL_HEAD_VehicleRestrictionsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_BODY_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_RemoveJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_RemoveJunction, Public_transport, Prevent_excessive_transfers_at_public_transport_stations, Compact_main_menu, Window_transparency, Overlay_transparency, Remove_this_citizen, Remove_parked_vehicles, Node_is_level_crossing, Experimental_features, Also_apply_to_left/right_turns_between_one-way_streets, Scan_for_known_incompatible_mods_on_startup, Ignore_disabled_mods, Traffic_Manager_detected_incompatible_mods, Notify_me_if_there_is_an_unexpected_mod_conflict,

### ru is 98% complete. Missing 4 keys:

TMPE_Title, Individual_driving_styles, TMPE_TUTORIAL_HEAD_MainMenu, TMPE_TUTORIAL_BODY_MainMenu,

### zh is 99% complete. Missing 1 keys:

Individual_driving_styles,

### zh-tw is 73% complete. Missing 63 keys:

Individual_driving_styles, Simulation, On_roads, Ban_private_cars_and_trucks_on_bus_lanes, default, flow_ratio, wait_ratio, After_min._time_has_elapsed_switch_to_next_step_if, Adaptive_step_switching, Dynamic_lane_section, Percentage_of_vehicles_performing_dynamic_lane_section, Vehicle_restrictions_aggression, Strict, Show_path-find_stats, Remove_this_vehicle, Vehicles_follow_priority_rules_at_junctions_with_timed_traffic_lights, Enable_tutorial_messages, TMPE_TUTORIAL_HEAD_MainMenu, TMPE_TUTORIAL_BODY_MainMenu, TMPE_TUTORIAL_HEAD_JunctionRestrictionsTool, TMPE_TUTORIAL_BODY_JunctionRestrictionsTool, TMPE_TUTORIAL_HEAD_LaneArrowTool, TMPE_TUTORIAL_BODY_LaneArrowTool, TMPE_TUTORIAL_HEAD_LaneConnectorTool, TMPE_TUTORIAL_BODY_LaneConnectorTool, TMPE_TUTORIAL_HEAD_ManualTrafficLightsTool, TMPE_TUTORIAL_BODY_ManualTrafficLightsTool, TMPE_TUTORIAL_HEAD_ParkingRestrictionsTool, TMPE_TUTORIAL_BODY_ParkingRestrictionsTool, TMPE_TUTORIAL_HEAD_PrioritySignsTool, TMPE_TUTORIAL_BODY_PrioritySignsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool, TMPE_TUTORIAL_BODY_SpeedLimitsTool, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool, TMPE_TUTORIAL_HEAD_ToggleTrafficLightsTool, TMPE_TUTORIAL_BODY_ToggleTrafficLightsTool, TMPE_TUTORIAL_HEAD_VehicleRestrictionsTool, TMPE_TUTORIAL_HEAD_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_BODY_SpeedLimitsTool_Defaults, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddStep, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_Copy, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_AddJunction, TMPE_TUTORIAL_HEAD_TimedTrafficLightsTool_RemoveJunction, TMPE_TUTORIAL_BODY_TimedTrafficLightsTool_RemoveJunction, Public_transport, Prevent_excessive_transfers_at_public_transport_stations, Compact_main_menu, Window_transparency, Overlay_transparency, Remove_this_citizen, Remove_parked_vehicles, Node_is_level_crossing, Experimental_features, Turn_on_red, Also_apply_to_left/right_turns_between_one-way_streets, Scan_for_known_incompatible_mods_on_startup, Ignore_disabled_mods, Traffic_Manager_detected_incompatible_mods, Notify_me_if_there_is_an_unexpected_mod_conflict,

**Comment by aubergine10** [comment]
Here's the xml file, and the (hastily bodged together) html file I used to create the `<Translations>` section:

[lang.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3267666/lang.zip)

Now we have an xml file, I'm pretty sure I can make a web page for editing that file = translators won't need to worry about the XML file, they'll just see a form with the keys vs. values.

**Comment by krzychu124** [comment]
Great but not 100% accurate 😉  Some translations doesn't have to be translated because they are the same meaning e.g. in Polish `Start`, `Stop` or `Segment`
To take that case into account we should differentiate translation keys a little bit (e.g. use capital letters).

**Comment by aubergine10** [comment]
> Great but not 100% accurate 😉 Some translations doesn't have to be translated because they are the same meaning e.g. in Polish Start, Stop or Segment

I already filtered out all translations that were exact match of English. :)

**Comment by Emphasia** [comment]
> ### zh is 99% complete. Missing 1 keys:
> Individual_driving_styles,

the missing 1 key of zh:
`Individual_driving_styles 个人驾驶风格`
@aubergine10

**Comment by aubergine10** [comment]
Busy writing web interface for maintaining the xml file, and found a few useful resources while searching for infos:

* https://github.com/umpirsky/language-list
* https://github.com/umpirsky/locale-list
* https://github.com/umpirsky/country-list

Specifically, on the "Add language" screen, I'm hoping to provide a list of existing languages so translators don't need to go hunting for the ISO codes. The second link above looks like it will do.

**Comment by aubergine10** [comment]
Just some to-do's for the webapp so I don't forget:

- [ ] Add `<Where>` tags in `<Translation>` tags; define where a translation is used
- [ ] Add `<Notes>` tags at top of `<Localization>` with some pointers to the web app
- [ ] Add `outdated="true"` attribute to `<Value>` tags to indicate which translations need updating due to alterations to the English translation (e.g. we refine an existing value, the other languages need to be updated)

**Comment by kvakvs** [comment]
What is this format?
What is the tool to edit it?
If the format is custom or there are no good tools, then this "new" format is just as bad as the old one.

I would suggest looking at Transifex, they offer free access for opensource projects and it is a well known tool for translating apps.

**Comment by kvakvs** [comment]
How is this check relevant to translating an open-source project?
If you use GDPR (the right to be forgotten) I am sure they are able to help you. But this is not relevant to i18n/l10n.

**Comment by aubergine10** [comment]
> How is this check relevant to translating an open-source project?

If you don't get why stuff like that is so important, there's no way I could ever explain it to you until it affects you personally.

> There was one more similar tool for this, crowdin

Looks better, will give it a try.

**Comment by kvakvs** [comment]
> If you don't get why stuff like that is so important, there's no way I could ever explain it to you until it affects you personally.

I live in Sweden, all my personal data (not private data) is publicly available online, including home address, employer, phone number, owned vehicles i think income bracket might also be known. In any case GDPR should be protecting me in such cases when I want stuff deleted from some website.

**Comment by aubergine10** [comment]
I repeat:

> there's no way I could ever explain it to you until it affects you personally.

**Comment by aubergine10** [comment]
Implemented in PR #509
