### ISSUE TITLE
Speeds Tool v2

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#84]
This supersedes #52 and #12.

**UI Tab**

- [ ] Requires #51 (toolbar -> build bar)
- [ ] Icon for "speeds" tab
- [ ] Resize speed icons to fit build bar?

**Toggle between segment vs. lane mode:**

- [ ] New UI "side" button for persistent toggle
- [ ] Ctrl+whatever = temporary toggle current state of button
- [ ] In segment mode, speed is set for *both directions*

**Apply speed changes:**

> When applying to a road segment, speed only gets applied to road lanes:
> * Monorail tracks get their own set of icons
> * Tram tracks, if separate from road lane, get own icons
>     * If part of road lane, they get same speed as road lane
> * Rail tracks: Treat same way as tram tracks

- [ ] Highlight segment/lane that will be affected
- [ ] Click = set speed for a segment/lane
- [ ] Shift+Click = Like Click, but propagates to nearest junction / dead-end
- [ ] Click+Drag = Applies Click to all segments/lanes dragged over
- [ ] Facilitate mph vs. km/h? See: #13 

**Clear speed changes:**

- [ ] Eraser tool (done as part of #51?)

**Default speeds:**

- [ ] Rubber stamp button?
- [ ] or Alt+Click?
- [ ] Store default speeds in global settings rather than savegame

**Comment by ntoff** [comment]
>After setting desired speeds for a segment, rubber stamp it to set as defaults

Could there also be a shortcut like shift + click (sets all speeds along a segment) to set the same speed for all existing roads of that type? So if you have a bunch of roads already placed, you could do something like ctrl + shift + click and it'll set all roads in the city of type X to be that speed. Or will setting a default speed automatically set all existing roads of that type?

**Comment by aubergine10** [comment]
Yes, see Alt+Click near end of opening post.
